"""
Service — Farm Diary Builder (Subsidy Focus)
Generates government-ready farm records and branded PDF reports.
"""
import json
import uuid
from typing import Dict, Any, List
from datetime import datetime, timezone
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from backend.models.state import FarmDiaryEntry
from backend.models.farm import Farm, Zone
from backend.services.water_usage import compute_water_used
from backend.utils.logger import logger

class DiaryBuilder:
    def __init__(self, logo_path: str = "backend/static/logo.png"):
        self.logo_path = logo_path

    async def log_activity(
        self,
        farm_id: str,
        zone_id: str,
        activity_type: str, # "fertilizer", "harvest", "irrigation"
        title: str,
        body: str,
        metadata: Dict[str, Any],
        db: AsyncSession,
        is_subsidy: bool = True
    ):
        """Create a rich diary entry for subsidy tracking."""
        cost_val = metadata.get("cost", 0.0)
        
        entry = FarmDiaryEntry(
            farm_id=farm_id,
            zone_id=zone_id,
            entry_type=activity_type,
            title=title,
            body=body,
            is_subsidy_relevant=is_subsidy,
            subsidy_status="pending" if is_subsidy else None,
            cost=cost_val,
            record_data=json.dumps(metadata)
        )
        db.add(entry)
        await db.flush()
        return entry

    def generate_html_report(self, entry: FarmDiaryEntry, farm_name: str, zone_name: str) -> str:
        """Build a branded HTML template for the subsidy record."""
        meta = json.loads(entry.record_data) if entry.record_data else {}
        date_str = entry.created_at.strftime("%B %d, %Y")
        
        # Branded Template Logic
        html = f"""
        <html>
        <head>
            <style>
                @page {{ size: A4; margin: 2cm; }}
                body {{ font-family: 'Helvetica', sans-serif; color: #333; }}
                .header {{ border-bottom: 2px solid #0056b3; padding-bottom: 20px; margin-bottom: 30px; }}
                .logo {{ float: left; width: 120px; }}
                .company-name {{ float: right; text-align: right; color: #0056b3; }}
                .title {{ clear: both; text-align: center; font-size: 24px; margin-top: 50px; }}
                .details {{ margin-top: 30px; border-collapse: collapse; width: 100%; }}
                .details th, .details td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
                .details th {{ background-color: #f2f2f2; }}
                .footer {{ margin-top: 50px; font-size: 10px; color: #777; text-align: center; }}
            </style>
        </head>
        <body>
            <div class="header">
                <img src="file://{self.logo_path}" class="logo">
                <div class="company-name">
                    <h2>AQUASOL AI</h2>
                    <p>Intelligence in every drop</p>
                </div>
            </div>
            
            <div class="title">Official Farm Activity Record</div>
            
            <table class="details">
                <tr><th>Report ID</th><td>{str(entry.id).upper()[:8]}</td></tr>
                <tr><th>Date</th><td>{date_str}</td></tr>
                <tr><th>Farmer / Estate</th><td>{farm_name}</td></tr>
                <tr><th>Zone / Block</th><td>{zone_name}</td></tr>
                <tr><th>Activity Type</th><td>{entry.entry_type.upper()}</td></tr>
            </table>

            <h3>Activity Summary</h3>
            <p>{entry.body}</p>

            <h3>Technical Data</h3>
            <table class="details">
                {"".join([f"<tr><th>{k.replace('_', ' ').title()}</th><td>{v}</td></tr>" for k, v in meta.items()])}
            </table>
            
            <div class="footer">
                This document is electronically generated by AquaSol Intelligence Engine for Government Subsidy Compliance.
                Verification Code: {entry.id}
            </div>
        </body>
        </html>
        """
        return html

    async def get_subsidy_data_for_pdf(self, entry_id: str, db: AsyncSession):
        res = await db.execute(
            select(FarmDiaryEntry, Farm.name, Zone.name)
            .join(Farm, Farm.id == FarmDiaryEntry.farm_id)
            .join(Zone, Zone.id == FarmDiaryEntry.zone_id)
            .where(FarmDiaryEntry.id == entry_id)
        )
        return res.first()

diary_builder = DiaryBuilder()
