"""initial_v3_topology

Revision ID: a3f52fb2dea2
Revises: 
Create Date: 2026-05-13 23:55:47.220032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3f52fb2dea2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_bio_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('water_req_mm', sa.Integer(), nullable=True),
    sa.Column('osmotic_shock_sensitive', sa.Boolean(), nullable=True),
    sa.Column('rrc_max_mm_per_cycle', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rrc_stage_split', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('temp_stress_threshold_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temp_optimal_min_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temp_optimal_max_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tsi_threshold', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('kc_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stages_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('soil_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_bio_profiles_name'), 'crop_bio_profiles', ['name'], unique=True)
    op.create_table('message_templates',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('en', sa.String(), nullable=False),
    sa.Column('hi', sa.String(), nullable=True),
    sa.Column('kn', sa.String(), nullable=True),
    sa.Column('te', sa.String(), nullable=True),
    sa.Column('ta', sa.String(), nullable=True),
    sa.Column('mr', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_message_templates_code'), 'message_templates', ['code'], unique=False)
    op.create_table('pairing_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('pairing_code', sa.String(length=8), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('is_master', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pairing_code')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('auth_provider', sa.String(), nullable=True),
    sa.Column('preferred_lang', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('farms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('total_acres', sa.Integer(), nullable=True),
    sa.Column('zones_per_acre', sa.Integer(), nullable=True),
    sa.Column('water_source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acres',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('size', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('acre_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('crop_type', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('soil_type', sa.String(), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=True),
    sa.Column('operating_mode', sa.String(length=50), nullable=True),
    sa.Column('area_acres', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sowing_date', sa.Date(), nullable=True),
    sa.Column('current_stage', sa.String(), nullable=True),
    sa.Column('expected_harvest', sa.Date(), nullable=True),
    sa.Column('morning_window', sa.String(), nullable=True),
    sa.Column('evening_window', sa.String(), nullable=True),
    sa.Column('min_moisture_threshold', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_moisture_threshold', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_irrigation_duration_sec', sa.Integer(), nullable=True),
    sa.Column('sensor_depth_cm', sa.Integer(), nullable=True),
    sa.Column('root_depth_cm', sa.Integer(), nullable=True),
    sa.Column('application_rate_mm_hr', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('efficiency', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('irrigation_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acre_id'], ['acres.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crop_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('crop_name', sa.String(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('weekly_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fertilizer_schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('irrigation_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('water_required_mm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cycles', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('policy_blocked', sa.Boolean(), nullable=True),
    sa.Column('block_reason', sa.String(), nullable=True),
    sa.Column('feature_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ood_flag', sa.Boolean(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diary_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('entry_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('is_subsidy_relevant', sa.Boolean(), nullable=True),
    sa.Column('subsidy_status', sa.String(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('payment_reference', sa.String(), nullable=True),
    sa.Column('record_data', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('acre_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('intensity', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acre_id'], ['acres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valve_commands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('mqtt_topic', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_duration_min', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zone_state',
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('current_moisture', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('predicted_moisture_1h', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('predicted_moisture_6h', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('predicted_moisture_24h', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('target_moisture_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('target_moisture_max', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('current_stage', sa.String(), nullable=True),
    sa.Column('stage_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('days_after_planting', sa.Integer(), nullable=True),
    sa.Column('last_irrigation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_irrigation_duration', sa.Integer(), nullable=True),
    sa.Column('valve_state', sa.String(), nullable=False),
    sa.Column('moisture_at_irrigation_start', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weather_rain_prob_6h', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weather_temp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ai_recommendation', sa.String(), nullable=True),
    sa.Column('model_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('uncertainty_flag', sa.String(), nullable=True),
    sa.Column('rolling_avg_24h', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('moisture_at_irrigation_end', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('expected_gain_mm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('execution_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('zone_id')
    )
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('node_slot_id', sa.UUID(), nullable=True),
    sa.Column('device_uid', sa.String(), nullable=False),
    sa.Column('pairing_code', sa.String(), nullable=True),
    sa.Column('device_secret', sa.String(), nullable=True),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('is_master', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_claimed', sa.Boolean(), nullable=False),
    sa.Column('node_label', sa.String(), nullable=True),
    sa.Column('firmware_version', sa.String(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('trust_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_slot_id'], ['node_slots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_uid'),
    sa.UniqueConstraint('mac_address'),
    sa.UniqueConstraint('pairing_code')
    )
    op.create_table('sensor_readings',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('node_slot_id', sa.UUID(), nullable=True),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('soil_moisture', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('valve_status', sa.Boolean(), nullable=True),
    sa.Column('flow_rate', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('total_water', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('rain_detected', sa.Boolean(), nullable=True),
    sa.Column('battery_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('solar_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('solar_voltage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_virtual', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['node_slot_id'], ['node_slots.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('time', 'device_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_readings')
    op.drop_table('devices')
    op.drop_table('zone_state')
    op.drop_table('valve_commands')
    op.drop_table('schedules')
    op.drop_table('node_slots')
    op.drop_table('diary_entries')
    op.drop_table('decision_log')
    op.drop_table('crop_plans')
    op.drop_table('zones')
    op.drop_table('acres')
    op.drop_table('farms')
    op.drop_table('users')
    op.drop_table('pairing_sessions')
    op.drop_index(op.f('ix_message_templates_code'), table_name='message_templates')
    op.drop_table('message_templates')
    op.drop_index(op.f('ix_crop_bio_profiles_name'), table_name='crop_bio_profiles')
    op.drop_table('crop_bio_profiles')
    # ### end Alembic commands ###
